//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package tk.woppo.sunday.service;

import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.os.Handler;
import android.os.Looper;

public final class WeatherUpdateService_
    extends WeatherUpdateService
{

    private Handler handler_ = new Handler(Looper.getMainLooper());

    public static WeatherUpdateService_.IntentBuilder_ intent(Context context) {
        return new WeatherUpdateService_.IntentBuilder_(context);
    }

    public static WeatherUpdateService_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new WeatherUpdateService_.IntentBuilder_(fragment);
    }

    public static WeatherUpdateService_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new WeatherUpdateService_.IntentBuilder_(supportFragment);
    }

    @Override
    public void updateWeather() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                WeatherUpdateService_.super.updateWeather();
            }

        }
        );
    }

    @Override
    public void updateTime() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                WeatherUpdateService_.super.updateTime();
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, WeatherUpdateService_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, WeatherUpdateService_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, WeatherUpdateService_.class);
        }

        public Intent get() {
            return intent_;
        }

        public WeatherUpdateService_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public ComponentName start() {
            return context_.startService(intent_);
        }

        public boolean stop() {
            return context_.stopService(intent_);
        }

    }

}
