//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package tk.woppo.sunday.ui.adapter;

import android.content.Context;

public final class MyCityAdapter_
    extends MyCityAdapter
{

    private Context context_;

    private MyCityAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static MyCityAdapter_ getInstance_(Context context) {
        return new MyCityAdapter_(context);
    }

    private void init_() {
        mContext = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
