//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package tk.woppo.sunday.ui.adapter;

import android.content.Context;

public final class SimpleWeatherAdapter_
    extends SimpleWeatherAdapter
{

    private Context context_;

    private SimpleWeatherAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static SimpleWeatherAdapter_ getInstance_(Context context) {
        return new SimpleWeatherAdapter_(context);
    }

    private void init_() {
        mContext = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
