//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package tk.woppo.sunday.ui.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;
import tk.woppo.sunday.R.layout;

public final class DrawerFragment_
    extends DrawerFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_drawer, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static DrawerFragment_.FragmentBuilder_ builder() {
        return new DrawerFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tvGanmao = ((TextView) hasViews.findViewById(tk.woppo.sunday.R.id.drawer_ganmao));
        tvTigan = ((TextView) hasViews.findViewById(tk.woppo.sunday.R.id.drawer_tigan));
        tvChuanyi = ((TextView) hasViews.findViewById(tk.woppo.sunday.R.id.drawer_chuanyi));
        tvTemp = ((TextView) hasViews.findViewById(tk.woppo.sunday.R.id.drawer_temp));
        ivWeatherImg = ((ImageView) hasViews.findViewById(tk.woppo.sunday.R.id.drawer_weather_img));
        tvXiche = ((TextView) hasViews.findViewById(tk.woppo.sunday.R.id.drawer_xiche));
        tvWeather = ((TextView) hasViews.findViewById(tk.woppo.sunday.R.id.drawer_tv_weather));
        tvYundong = ((TextView) hasViews.findViewById(tk.woppo.sunday.R.id.drawer_yundong));
        tvZhiwaixian = ((TextView) hasViews.findViewById(tk.woppo.sunday.R.id.drawer_ziwaixian));
        ivWeather = ((ImageView) hasViews.findViewById(tk.woppo.sunday.R.id.drawer_weather));
        {
            View view = hasViews.findViewById(tk.woppo.sunday.R.id.drawer_del_city);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DrawerFragment_.this.clickDelCity();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(tk.woppo.sunday.R.id.drawer_exit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DrawerFragment_.this.clickExit();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(tk.woppo.sunday.R.id.drawwer_setting);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DrawerFragment_.this.clickSetting();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(tk.woppo.sunday.R.id.drawer_add_city);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DrawerFragment_.this.clickAddCity();
                    }

                }
                );
            }
        }
        initFragment();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public DrawerFragment build() {
            DrawerFragment_ fragment_ = new DrawerFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
