//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package tk.woppo.sunday.widget;

import android.app.Fragment;
import android.content.Context;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.ImageView;
import android.widget.TextView;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;
import tk.woppo.sunday.R.id;
import tk.woppo.sunday.R.layout;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class TodayWeatherItem_
    extends TodayWeatherItem
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public TodayWeatherItem_(Context context, Fragment fragment) {
        super(context, fragment);
        init_();
    }

    public static TodayWeatherItem build(Context context, Fragment fragment) {
        TodayWeatherItem_ instance = new TodayWeatherItem_(context, fragment);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.layout_weather_today, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tvCreateTiem = ((TextView) hasViews.findViewById(id.tv_create_time));
        ivWeatherIcon = ((ImageView) hasViews.findViewById(id.iv_weather_icon));
        tvTemp = ((TextView) hasViews.findViewById(id.tv_temp));
        tvWeather = ((TextView) hasViews.findViewById(id.tv_weather));
        tvWind = ((TextView) hasViews.findViewById(id.tv_wind));
        tvCity = ((TextView) hasViews.findViewById(id.tv_city));
        {
            View view = hasViews.findViewById(id.tv_city);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        TodayWeatherItem_.this.cityClick();
                    }

                }
                );
            }
        }
    }

}
